### ISSUE TITLE
Review: AI Gen Examples for `numpy.linalg.svdvals` function

### ISSUE THREAD

**Issue by ogidig5** [possee-org/genai-numpy#86]
https://github.com/numpy/numpy/compare/main...ogidig5:numpy:add-svdvals-example

Here's what reflects when the docs build:

![Cleaned svdvals example](https://github.com/possee-org/genai-numpy/assets/82846833/8c5ce9df-96d1-4d10-944f-1d95a2dd06cc)

**Checks**

```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests
```
- [ ] All tests have passed
- [ ] A visual inspection of the generated docs is correct

**Acceptance Criteria:**

Close when the following are complete, in order:
- [ ] Reviewed by @bmwoodruff
- [ ] Any suggestions to fork have been merged.
- [ ] Reviewed by Numpy Mainter:

When all tasks are complete:
- [ ] Submitted as PR to NumPy.

**Comment by ogidig5** [comment]
Let me check the syntax of this function and make sure it runs well on the Jupyter Notebook

**Comment by bmwoodruff** [comment]
Viewing the docs is not the same as running the doctests with `python toos/refguide_check --doctests`.

**Comment by ogidig5** [comment]
I really need to quickly meet up with you. Seems I'm missing something crucial in the process. I want to work on that through the day

**Comment by ogidig5** [comment]
I've been able to figure out the authentication issue. Here's the current changes pushed to my fork: https://github.com/numpy/numpy/compare/main...ogidig5:numpy:add-svdvals-example

**Comment by bmwoodruff** [comment]
You'll want to update the images to be current. Just edit your original message, so the new image shows up front. 
Just about everything looks good now, with one issue:

- I ran the doctests, and they failed.

Did you run the tests?  In particular, did you run `python tools/refguide_check.py --doctests`.  You must run all the tests. This should have failed on your machine as we didn't set a seed.

The tests failed because the matrix values are random. You have to add `# may vary` or `# random` after the output , otherwise the tests will fail. This is what the relevant code could look like. 
```
...
    array([2.05175379, 0.75852089, 0.10363495]) # may vary
...
    array([[1.59357377, 0.2369699 , 0.03501063],  # may vary
           [2.00939638, 0.39010965, 0.06555355]])
...
    array([2.35955923, 0.67914258, 0.15643921])  # may vary
``` 

Please run the doctests, and verify that the test fails before you make the change. If all you run is `python tools/refguide_check.py --doctests`, that isn't enough. You first have to build the docs, then install numpy, and then you can run that function. The entire string of commands you need is
```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests && spin lint
```
 AFTER you have verified the doctests failed, then make the change by adding `# may vary`. Then test them again (build numpy, install it, run the doc tests)
```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests && spin lint
```
Then try changing `# may vary` to `# random`, and verify you pass the tests as well. 

Glad you submitted this one. It's another thing I need to add to automation.  I'll have to add a checker to see if "random" values are entered, and then add this to the first line of output.

**Comment by bmwoodruff** [comment]
Here is the error message I got:
![Screenshot from 2024-06-19 13-49-38](https://github.com/possee-org/genai-numpy/assets/1594818/f96afc4e-90dd-48e9-99e3-83a7a55a7609)

**Comment by bmwoodruff** [comment]
I'm going to close this one. It isn't passing the tests, and the internship has ended. I think it's just missing the `# may vary` tag before it will pass the tests.
