### ISSUE TITLE
Review: AI Gen Examples for ma.dot, ma.cumsum and ma.prod

### ISSUE THREAD

**Issue by jud-sdev** [possee-org/genai-numpy#87]
https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func
 Here are the screensots of the compiled docs
![madot](https://github.com/possee-org/genai-numpy/assets/147154874/57e1914d-24ea-4da5-8eeb-004e4b537a8c)

![macumsum](https://github.com/possee-org/genai-numpy/assets/147154874/e3ab052c-9127-48ca-90d5-92b794d412a5)

![maprod](https://github.com/possee-org/genai-numpy/assets/147154874/71a441a6-b7c4-4dd4-b58d-826d29493252)

**Checks**

```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests
```
- [x] All tests have passed
- [x] A visual inspection of the generated docs is correct

**Acceptance Criteria:**

Close when the following are complete, in order:
- [ ] Reviewed by @bmwoodruff
- [ ] Any suggestions to fork have been merged.
- [ ] Reviewed by Numpy Mainter:

When all tasks are complete:
- [ ] Submitted as PR to NumPy.

**Comment by bmwoodruff** [comment]
ma.dot is on line 7984 of the original file.  You've added examples to the wrong place. Check the file again, and you'll notice it appears in two places. 
- The examples section is also always below the See also section (check surrounding functions). 
- Also, avoiding adding extra spaces that are not related to your change (see line 5211 in your changed work). 

ma.cumsum
- Can you upload your log from llama3-70B and provide a link to it in the logs.  I apparently missed this one. I'm wondering why there are no words between examples.  Most of the time, llama3 has been providing some words between examples, and I think those are useful to keep. These words often explain why the new example matters.  If it didn't generate any words, that's OK.  I'm just wondering why they aren't there.  Please add the output from Llama3B into the log files, and then provide a link here.
- Your work changed two lines from a different function (5303 and 5304). Avoid that.
- The code runs with the correct output.  I haven't build numpy with this change yet, nor run the doctests. I'll do so when ma.dot is updated. 

ma. prod
- Upload your log from llama3 to the logs folders on genai-numpy. 
- Were there words between examples?  
- Right now this function has too many examples.  The first and last are almost the same.  Without the words between examples, there doesn't seem to be a reason to have this many examples. Those words are crucial.
- You can remove the np.int64 from things.  I think it's interesting that type information shows for all the examples except the one that uses dtype.

**Comment by bmwoodruff** [comment]
Did you run the doctests?

**Comment by bmwoodruff** [comment]
Your work on ma.cumsum has helped me find more functions that we can search through. Typing `help(np.ma.cumsum)` shows `Help on _frommethod in module numpy.ma.core`. This is the same message which appears with `ma.prod`. 

Just wondering, why did you pick these two functions in particular? Did you look for ones that the script missed, or was it arbitrary?

**Comment by jud-sdev** [comment]
I ran doctests.
In our conversation last week, you said `ma` has so many functions, and I can pick any function of my choice to practice with. So, I picked those three functions. Two of them are without examples while the third function has one example. 
For the ma.dot, I must have missed the lines, I'll put the examples where they're supposed to be.
There were words between the examples, but I removed them. I'll include the words in the next update.

**Comment by bmwoodruff** [comment]
Thanks for the reply I was wondering if you found some way to locate these specific functions (they have an odd type that I didn't know to search for).  The ma module is huge, so it's fine you chose these ones. I'm glad you did, because it showed me we were missing some things. 

The doctest question I asked because you didn't check that box. 

I'd love to have logs for these in on this site. Please add them and submit a PR to genai-numpy. 

When you see a function with 7 examples provided, you'll have to start deciding if they are all really needed. If you see some that are super similar, then trim it down. This is subjective, so I think over time we'll learn how to trim things down.

**Comment by jud-sdev** [comment]
I've made the suggested changes. Meanwhile, I got indentation warnings/errors when I built the doc. I tried adjusting it, but it's not still working. I'll need your help on this.
I have the three functions in 1 log file. Since I've already created the log on Thurday, before the latest instruction of having 1 log per function.
Here the link to the log: https://github.com/possee-org/genai-numpy/blob/e949a3f321a881288513d989d8d2885a4ac3096d/examples/log/np_ma/ma.ex.log

**Comment by bmwoodruff** [comment]
When you get errors and aren't sure what they mean, please put them in a code block and share them. 
```
Paste errors here
```
That can help identify the issue. I'll checkout your branch now and run the tests on my machine to see if I can find the issue.

**Comment by bmwoodruff** [comment]
@jud-sdev , look at line 5179 in https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func.  You can see quickly that you added spaces to a blank line, that should not have spaces added.

You will have other errors when you build things. Namely, the words between examples must be separated by a blank line from the examples.  So instead of
```
        Multiple axes:
        >>> np.ma.prod(np.ma.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]), axis=(0, 2))
        masked_array(data=[ 60, 672],
            mask=False,
            fill_value=999999)
```
you need
```
        Multiple axes:

        >>> np.ma.prod(np.ma.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]), axis=(0, 2))
        masked_array(data=[ 60, 672],
            mask=False,
            fill_value=999999)
```

AI did not get proper spacing.  This is something we have to clean up. If you run this, and then try to view the docs, you'll find it looks horrible.

**Comment by bmwoodruff** [comment]
One last comment:  Use this link 
* https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func
instead of
* https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func?expand=1
and the Pull Request editor won't auto open. 

The only difference is the `?expand=1` at the end of the URL.

**Comment by jud-sdev** [comment]
Thank you @bmwoodruff . I'll make the corrections and spin the docs and run the tests again.

**Comment by jud-sdev** [comment]
It worked fine now and passed the tests. Thank you.
https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func

**Comment by bmwoodruff** [comment]
This looked great to me, and then I ran one more test which I didn't list above (glad you helped me realize we must include it).
```
spin(lint)
```
Try running that test and you'll see that there are 4 lines that are too long. Those 4 lines need to be shortened. 
One of the lines was original code that you modified (the first). 
Update the file to make sure the lines are the proper length, and run the tests again.

Once you have finished that, it's time to learn how to `rebase` and `squash` to main, squashing all your commits to one. That way there is only one commit showing when you submit a PR.

Here's an example of how you can create a new branch on which to practice rebasing. 
```
git checkout main
git pull upstream main --tags
git submodule update --init
git checkout ma-func
git checkout -b ma-func-squashed
```
The above makes sure you have the most recent version of `main` from numpy, and then creates a new branch `ma-fun-squashed` based on `ma-func` (that's why we did `checkout ma-func` first). Because we are on a new branch, if you mess anything up along the way, it's easy to just do a `git branch -D ma-func-squashed` to remove the branch, and then start again.

Type the following:
```
git log
```
You'll see that you have many commits. It would be nice if this were a single commit. 

Now we rebase to main and squash the commits into a single commit.
```
git rebase -i main
```
This will open an editor showing all the commits you have back to `main`. Leave the first row alone. In the other rows, change `pick` to `squash`. Then save the file (Ctrl + S) and exit the editor (Ctrl + X). A second window will appear that contains all the commit messages along the way. You can now write a single simple commit message, deleting everything else.  When you save and exit, git will squash everything to a single commit. View that your work is now just one commit away from main. 
```
git log
```
Now delete the branch `ma-func-squashed` and try this again. Make up another name for a branch, base if on your `ma-func` branch, and practice squashing to main. Delete this new practice branch when you're done, and repeat it a few times.

When you feel comfortable with all this, checkout `ma-func` and squash to main `git rebase -i main`. If everything goes well, then can push the changes online with 
```
git push -f origin ma-func
```
The `-f` is required, as you have to force push the changes over the top of what's currently online.

**Comment by jud-sdev** [comment]
Thank you. I'll work on that.

**Comment by jud-sdev** [comment]
I've corrected the line length issue and I've squashed all the commits into one. Thanks Ben for all the helps. I'm really learning alot.
https://github.com/numpy/numpy/compare/main...jud-sdev:numpy:ma-func

**Comment by bmwoodruff** [comment]
Here's a few things to update:

- Line 5179: You made a change to the original codebase that has nothing to do with this PR.  Remember to avoid that. 
- Line 5272-5272: You made more changes to the original examples that were there.
- We won't be submitting examples for functions that already have them, so two of the functions you can remove. 

It would probably be simpler to start from scratch, bring in just the examples for `ma.prod`, and then create a PR for that. Start a new branch with this name (maybe ma-prod-examples) and then submit that for review.

I'm not sure what value the final example provides for ma.prod.  Delete it. Once you submit a new branch for review, please close this one.

**Comment by bmwoodruff** [comment]
I'm also getting a bunch of errors when trying to build the docs:
```
WARNING: autodoc: failed to import function 'cumulative_prod' from module 'numpy'; the following exception was raised:
... (goes on for 20+ lines)
```
Update your main branch, then checkout a new clean branch, complete a review on just the `ma.prod` function. Then submit that for review.  I'm going to close this task, and let you open another.  You can delete the ma-func branch.
